In [1]:
import sys
import torch
import os
from os import makedirs
import numpy as np
import open3d as o3d
from random import randint
from scipy.spatial.transform import Rotation
from tqdm import tqdm
import matplotlib.pyplot as plt
import cv2
import math
import random

np.set_printoptions(suppress=True)


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
def getWorld2View2(R, t, translate=np.array([.0, .0, .0]), scale=1.0):
    Rt = np.zeros((4, 4))
    Rt[:3, :3] = R.transpose()
    Rt[:3, 3] = t
    Rt[3, 3] = 1.0

    C2W = np.linalg.inv(Rt)
    cam_center = C2W[:3, 3]
    cam_center = (cam_center + translate) * scale
    C2W[:3, 3] = cam_center
    Rt = np.linalg.inv(C2W)
    return np.float32(Rt)

def qvec2rotmat(qvec):
    return np.array([
        [1 - 2 * qvec[2]**2 - 2 * qvec[3]**2,
         2 * qvec[1] * qvec[2] - 2 * qvec[0] * qvec[3],
         2 * qvec[3] * qvec[1] + 2 * qvec[0] * qvec[2]],
        [2 * qvec[1] * qvec[2] + 2 * qvec[0] * qvec[3],
         1 - 2 * qvec[1]**2 - 2 * qvec[3]**2,
         2 * qvec[2] * qvec[3] - 2 * qvec[0] * qvec[1]],
        [2 * qvec[3] * qvec[1] - 2 * qvec[0] * qvec[2],
         2 * qvec[2] * qvec[3] + 2 * qvec[0] * qvec[1],
         1 - 2 * qvec[1]**2 - 2 * qvec[2]**2]])

In [3]:
# Camera Intrinsics
rgb_camera_params = {}
depth_camera_params = {}
relative_positions = {}

def readRGBDConfig(config_file):
    # Define dictionaries to hold camera parameters
    # rgb_camera_params = {}
    # depth_camera_params = {}
    # relative_positions = {}
    
    with open(config_file, 'r') as file:
        data = file.read().split('\n\n')
    
        # Read RGB camera parameters
        rgb_data = data[0].split('\n')
        for line in rgb_data[1:4]:
            key, value = line.split('=')
            if ',' in value:
                value = tuple(map(float, value.split(',')))
            else:
                value = tuple(map(int, value.split('x')))
            rgb_camera_params[key] = value

        vFOV, hFOV = rgb_data[4].split(',')
        key, value = vFOV.split('=')
        rgb_camera_params[key] = float(value.strip('°'))
        key, value = hFOV.split('=')
        rgb_camera_params[key.strip(' ')] = float(value.strip('°'))

        # Read Depth camera parameters
        depth_data = data[1].split('\n')
        for line in depth_data[1:4]:
            key, value = line.split('=')
            if ',' in value:
                value = tuple(map(float, value.split(',')))
            else:
                value = tuple(map(int, value.split('x')))
            depth_camera_params[key] = value

        vFOV, hFOV = depth_data[4].split(',')
        key, value = vFOV.split('=')
        depth_camera_params[key] = float(value.strip('°'))
        key, value = hFOV.split('=')
        depth_camera_params[key.strip(' ')] = float(value.strip('°'))

    
        # Read relative positions of camera components
        rel_pos_data = data[2].split('\n')
        for line in rel_pos_data[1:]:
            key, value = line.split(': ')
            value = tuple(map(float, value.strip('(').strip(')').split(',')))
            relative_positions[key] = value

        return rgb_camera_params, depth_camera_params, relative_positions
    
    # Access the loaded camera parameters
    print("RGB Camera Parameters:")
    print(rgb_camera_params)
    
    print("\nDepth Camera Parameters:")
    print(depth_camera_params)
    
    # print("\nRelative Positions of Camera Components:")
    # print(relative_positions)

config_file = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV1\\config\\configuration.txt"
# config_file = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV2\\configuration.txt"
readRGBDConfig(config_file)

({'resolution': (1920, 1080),
  'cx,cy,fx,fy': (959.5, 539.5, 960.0, 960.0),
  'k1,k2,k3,p1,p2': (0.0, 0.0, 0.0, 0.0, 0.0),
  'vFov': 58.7155,
  'hFov': 90.0},
 {'resolution': (512, 424),
  'cx,cy,fx,fy': (255.5, 211.5, 256.0, 256.0),
  'k1,k2,k3,p1,p2': (0.0, 0.0, 0.0, 0.0, 0.0),
  'vFov': 79.2579,
  'hFov': 89.9999},
 {'RGB sensor': (0.0, 0.0, 0.0),
  'RGB light source': (0.0, 0.3, 0.0),
  'RGB light source size': (0.4, 0.4),
  'Depth sensor': (0.03, 0.0, 0.0),
  'Depth light source': (0.06, 0.0, 0.0),
  'Depth light source size': (0.02, 0.02)})

In [4]:
cx = rgb_camera_params['cx,cy,fx,fy'][0]
cy = rgb_camera_params['cx,cy,fx,fy'][1]
fx = rgb_camera_params['cx,cy,fx,fy'][2] 
fy = rgb_camera_params['cx,cy,fx,fy'][3]

k1 = rgb_camera_params['k1,k2,k3,p1,p2'][0]
k2 = rgb_camera_params['k1,k2,k3,p1,p2'][1]
k3 = rgb_camera_params['k1,k2,k3,p1,p2'][2]
p1 = rgb_camera_params['k1,k2,k3,p1,p2'][3] 
p2 = rgb_camera_params['k1,k2,k3,p1,p2'][4]


# RGB Camera Intrinsic Matrix
K_rgb = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0, 0, 1]])

D_rgb = np.array([k1, k2, p1, p2, k3])

cx_tof = depth_camera_params['cx,cy,fx,fy'][0]
cy_tof = depth_camera_params['cx,cy,fx,fy'][1]
fx_tof = depth_camera_params['cx,cy,fx,fy'][2] 
fy_tof = depth_camera_params['cx,cy,fx,fy'][3]

k1_tof = rgb_camera_params['k1,k2,k3,p1,p2'][0]
k2_tof = rgb_camera_params['k1,k2,k3,p1,p2'][1]
k3_tof = rgb_camera_params['k1,k2,k3,p1,p2'][2]
p1_tof = rgb_camera_params['k1,k2,k3,p1,p2'][3] 
p2_tof = rgb_camera_params['k1,k2,k3,p1,p2'][4]


# TOF Camera Intrinsic Matrix
K_tof = np.array([[fx_tof, 0, cx_tof],
                  [0, fy_tof, cy_tof],
                  [0, 0, 1]])

D_tof = np.array([k1_tof, k2_tof, p1_tof, p2_tof, k3_tof])

print("RGB Camera Intrinsic Matrix:")
print(K_rgb)
print(D_rgb)
print("TOF Camera Intrinsic Matrix:")
print(K_tof)
print(D_tof)

# Relative translation
translation = np.array([0.03,0,0])  # Replace with your actual translation values

# Relative rotation
rotation = np.eye(3)  # Replace with your actual rotation matrix

# Compose transformation matrix
extrinsic_matrix = np.column_stack((rotation, translation))
tof_extrinsic_matrix = np.row_stack((extrinsic_matrix, [0, 0, 0, 1]))

print("Extrinsic Matrix:", tof_extrinsic_matrix)

RGB Camera Intrinsic Matrix:
[[960.    0.  959.5]
 [  0.  960.  539.5]
 [  0.    0.    1. ]]
[0. 0. 0. 0. 0.]
TOF Camera Intrinsic Matrix:
[[256.    0.  255.5]
 [  0.  256.  211.5]
 [  0.    0.    1. ]]
[0. 0. 0. 0. 0.]
Extrinsic Matrix: [[1.   0.   0.   0.03]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   1.  ]]


In [5]:
# Camera Extrinsics
pose_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV1\\config"
# pose_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV2\\trajectory"


config_files = os.listdir(pose_directory)
config_files.sort()

extrinsics = {}

# config_files[:5]
# for config_index in tqdm(range(5)):
for config_index in tqdm(range(len(config_files))):
    file = config_files[config_index]
    if file.startswith("campose-rgb-"):
        frame_id = file.split('-')[2].split('.')[0]
        config_file = os.path.join(pose_directory, file)
        # print(config_file)
        
        with open(config_file, 'r') as file:
            lines = file.readlines()

            # Extracting position
            position_str = lines[0].replace('position=', '').split('\n')[0]
            position = np.array([float(i) for i in position_str.strip('()').split(',')])

            # Extracting rotation as a quaternion
            rotation_str = lines[1].replace('rotation_as_quaternion=', '').split('\n')[0]
            rotation = np.array([float(i) for i in rotation_str.strip('()').split(',')])

            # Extracting the 4x4 pose matrix
            pose_str = lines[3:]
            pose = np.array([[float(i) for i in row.strip('(').split(')')[0].split(',')] for row in pose_str if row != ''])    

            # print('Position:', position)
            # print('Rotation:',rotation)
            # print('Pose:',pose)
            extrinsics[frame_id] = pose

print("Number of frames:", len(extrinsics))

100%|██████████| 601/601 [00:00<00:00, 7771.88it/s]

Number of frames: 300


In [6]:
# Directory where your images are stored
# rgb_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV1\\rgb"
# depth_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV1\\rgb"

depth_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV2\\gt_depth"
rgb_directory = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\SyntheticV2\\color"
ply_path = "G:\\Universitat Siegen\\SA\\P-GPU\\Code\\gaussian-splatting\\data\\RGBD_Data\\ply"

# Get the list of files in the directory
files = os.listdir(depth_directory)

# Sort the files to process depth and color images together
files.sort()

# Initialize an empty point cloud
point_cloud = o3d.geometry.PointCloud()

start_index = 0
ply_files = os.listdir(ply_path)
if len(ply_files) > 0:
    start_index = int(ply_files[-1].split('.')[0])

frame_step = 10
# Loop through each pair of depth and color images
# for i in tqdm(range(1)):

depth_files = [file for file in files if file.startswith("gt-rgb-depth-") ]
depth_files = depth_files[:50]

print("Number of files:", len(depth_files))
print("Start index:", start_index)

Number of files: 50
Start index: 0


In [6]:
point_cloud = o3d.geometry.PointCloud()

# Using Open3D to create point clouds
if False:
# for i in tqdm(range(start_index, len(depth_files),frame_step)):
# for i in range(start_index, 10 ,frame_step):
    depth_file_name = depth_files[i]
    # print(file)
    # if file.startswith("gt-rgb-depth-"):  # Check if the file is a depth image
    depth_file = os.path.join(directory, depth_file_name)
    
    # Get the corresponding color image
    color_file = os.path.join(directory, "rgb-" + depth_file_name[-8:])  # Assuming both files have corresponding indices
    
    frame_id = depth_file_name.split('-')[3].split('.')[0]

    # Read the depth and color images
    depth_image = cv2.imread(depth_file, cv2.IMREAD_UNCHANGED)
    depth_image = cv2.resize(depth_image, (512, 424), interpolation=cv2.INTER_NEAREST)
    color_image = cv2.imread(color_file, cv2.IMREAD_UNCHANGED)

    # Convert images to numpy arrays
    depth_array = np.asarray(depth_image)
    color_array = np.asarray(color_image)

    width = depth_array.shape[1]
    height = depth_array.shape[0]

    
    
    # Intrinsic parameters of the camera (you may need to adjust these values)
    intrinsic = o3d.camera.PinholeCameraIntrinsic()
    cx = depth_camera_params['cx,cy,fx,fy'][0]
    cy = depth_camera_params['cx,cy,fx,fy'][1]
    fx = depth_camera_params['cx,cy,fx,fy'][2] 
    fy = depth_camera_params['cx,cy,fx,fy'][3]
    intrinsic.set_intrinsics(width=width, height=height, cx=cx, cy=cy, fx=fx, fy=fy)

    # print("I:", intrinsic.intrinsic_matrix)
    # print("P:", extrinsics[frame_id])

    assert frame_id in extrinsics, "No pose found for frame " + frame_id

    pose = extrinsics[frame_id]

    # print("Frame:", frame_id)
    # print("Pose:", pose)

    # Extraction of rotation matrix (3x3 sub-matrix)
    rotation_matrix = pose[:3, :3]

    # Extraction of translation vector (last column)
    translation_vector = pose[:3, 3]

    # print(pose)
    # worldtoview = getWorld2View2(rotation_matrix, translation_vector)
    # print(rotation_matrix)
    # print(translation_vector)
    # print("W2V:", worldtoview)

    # Create a point cloud from the depth and color information
    rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(color_image, depth_image, depth_trunc=4.0, convert_rgb_to_intensity=False)
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd, intrinsic,extrinsic=pose)    
    pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))


    # Save the point cloud to a file
    ply_file_path = os.path.join(ply_path, frame_id + ".ply")    
    # o3d.io.write_point_cloud(ply_file_path, pcd)

    # Merge current point cloud with the overall point cloud
    point_cloud += pcd

    # Clear memory
    depth_image = None
    color_image = None
    depth_array = None
    color_array = None
    pcd = None


# Visualize the final point cloud
# o3d.visualization.draw_geometries([point_cloud])

In [24]:
# UVD Function based Implementation
point_cloud = o3d.geometry.PointCloud()
SAMPLE_RATIO = 0.05

def convert_from_uvd(u, v, d, intr, pose):
    if d == 0:
        return None, None, None
    
    fx = intr[0, 0]
    fy = intr[1, 1]
    cx = intr[0, 2]
    cy = intr[1, 2]
    depth_scale = 1000
    
    z = d / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    
    world = (pose @ np.array([x, y, z, 1]))
    return world[:3] / world[3]

# Using Numpy to create point clouds
# for i in tqdm(range(start_index, len(depth_files),frame_step)):
for i in range(0, 20,10):
    depth_file_name = depth_files[i]
    depth_file = os.path.join(depth_directory, depth_file_name)
    
    # Get the corresponding color image
    color_file = os.path.join(rgb_directory, "rgb-" + depth_file_name[-8:])  # Assuming both files have corresponding indices
    
    frame_id = depth_file_name.split('-')[3].split('.')[0]

    # Read the depth and color images
    depth_image = cv2.imread(depth_file, cv2.IMREAD_UNCHANGED)
    depth_image = cv2.resize(depth_image, (512, 424), interpolation=cv2.INTER_NEAREST)
    color_image = cv2.imread(color_file, cv2.IMREAD_UNCHANGED)
    color_image = cv2.resize(color_image, (512, 424), interpolation=cv2.INTER_NEAREST)

    # Convert images to numpy arrays
    depth_array = np.asarray(depth_image)
    color_array = np.asarray(color_image)
    
    width = depth_array.shape[1]
    height = depth_array.shape[0]

    assert frame_id in extrinsics, "No pose found for frame " + str(frame_id)
    intrinsic = o3d.camera.PinholeCameraIntrinsic()
    cx = depth_camera_params['cx,cy,fx,fy'][0]
    cy = depth_camera_params['cx,cy,fx,fy'][1]
    fx = depth_camera_params['cx,cy,fx,fy'][2] 
    fy = depth_camera_params['cx,cy,fx,fy'][3]
    intrinsic.set_intrinsics(width=width, height=height, cx=cx, cy=cy, fx=fx, fy=fy)
    intrinsic_matrix = np.array(intrinsic.intrinsic_matrix)
    # print("I:", intrinsic_matrix)

    pose = extrinsics[frame_id]

    # print("Frame:", frame_id)
    # print("Pose:", pose)

    x_local, y_local, z_local, rgb_local = [], [], [], []

    # Convert depth to float32 for accurate calculations
    depth_array = depth_array.astype(np.float32)

    for i in range(depth_array.shape[0]):
        for j in range(depth_array.shape[1]):
            # if random.random() < SAMPLE_RATIO:
            if True:
                x, y, z = convert_from_uvd(j, i, depth_array[i, j], intrinsic_matrix, pose)
                if x is None:
                    continue
        
                x_local.append(x)
                y_local.append(y)
                z_local.append(z)

                ci = int(i * color_array.shape[0] / depth_array.shape[0])
                cj = int(j * color_array.shape[1] / depth_array.shape[1])
                rgb_local.append(color_array[ci, cj] / 255.0)

    # Add the points to the local point cloud        
    point_cloud_local = np.vstack((x_local, y_local, z_local)).T
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(point_cloud_local)
    pcd.transform([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0],[0, 0, 0, 1]])
    # Add color to the point cloud
    # pcd.colors = o3d.utility.Vector3dVector(rgb_local)
    point_cloud += pcd

    # Clear memory
    depth_image = None
    color_image = None
    depth_array = None
    color_array = None
    pcd = None

# Create an Open3D mesh representing coordinate axes
axes = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])

# Visualize the final point cloud
o3d.visualization.draw_geometries([point_cloud, axes])

point_cloud_global = None
pcd = None
point_cloud = None
axes = None

In [11]:
# Resized Implementations

point_cloud = o3d.geometry.PointCloud()

# Using Numpy to create point clouds
for i in tqdm(range(start_index, len(depth_files),frame_step)):
# for i in range(start_index, len(files),frame_step):
# for i in tqdm(range(1)):
    depth_file_name = depth_files[i]
    depth_file = os.path.join(depth_directory, depth_file_name)
    
    # Get the corresponding color image
    color_file = os.path.join(rgb_directory, "rgb-" + depth_file_name[-8:])  # Assuming both files have corresponding indices
    
    frame_id = depth_file_name.split('-')[3].split('.')[0]

    # Read the depth and color images
    depth_image = cv2.imread(depth_file, cv2.IMREAD_UNCHANGED)
    depth_image = cv2.resize(depth_image, (512, 424), interpolation=cv2.INTER_NEAREST)
    color_image = cv2.imread(color_file, cv2.IMREAD_UNCHANGED)
    color_image = cv2.resize(color_image, (512, 424), interpolation=cv2.INTER_NEAREST)

    # Convert images to numpy arrays
    depth_array = np.asarray(depth_image)

    color_array = np.asarray(color_image)
    color_array = color_array[:, :, :3]

    # print(np.shape(color_array), np.shape(depth_array))

    # print(np.min(depth_array), np.max(depth_array))
    # print(np.min(color_array), np.max(color_array))

    width = depth_array.shape[1]
    height = depth_array.shape[0]

    # Intrinsic parameters of the camera (you may need to adjust these values)
    cx = depth_camera_params['cx,cy,fx,fy'][0]
    cy = depth_camera_params['cx,cy,fx,fy'][1]
    fx = depth_camera_params['cx,cy,fx,fy'][2] 
    fy = depth_camera_params['cx,cy,fx,fy'][3]

    # vFov = rgb_camera_params['vFov']
    # hFov = rgb_camera_params['hFov']
    # print("vFov:", vFov)
    # print("hFov:", hFov)
    # x_corr = math.tan(math.radians(hFov/2)) / (1920/2)
    # y_corr = math.tan(math.radians(vFov/2)) / (1080/2)

    print("Frame:", frame_id)
    assert frame_id in extrinsics, "No pose found for frame " + frame_id

    pose = extrinsics[frame_id]
    # pose = np.linalg.inv(pose)

    print(depth_file)
    print("Pose:", pose)

    # Convert depth to 3D coordinates in camera coordinates
    u, v = np.meshgrid(np.arange(width), np.arange(height))
    u = u.flatten()
    v = v.flatten()

    # Convert depth to float32 for accurate calculations
    depth_image = depth_image.astype(np.float32)
    depth_scale = 1000.0
    depth = depth_image.flatten() / depth_scale
    X = ((u - cx) * depth / fx)
    Y = ((v - cy) * depth / fy) 
    Z = depth

    # print(np.min(depth), np.max(depth))

    rgb_values = color_array.reshape((-1, 3)) / 255.0
    
    # Stack the 3D coordinates
    points_camera = np.vstack((X, Y, Z, np.ones_like(X)))

    if False:
        # Extract the transformed X, Y, Z coordinates
        X_local = points_camera[0, :]
        Y_local = points_camera[1, :]
        Z_local = points_camera[2, :]
        # Stack the global coordinates
        point_cloud_local = np.vstack((X_local, Y_local, Z_local)).T
        pcd = o3d.geometry.PointCloud()
        pcd.points = o3d.utility.Vector3dVector(point_cloud_local)
        pcd.transform([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0],[0, 0, 0, 1]])
        # Add color to the point cloud
        pcd.colors = o3d.utility.Vector3dVector(rgb_values)
        point_cloud += pcd

    # print("Frame:", frame_id)
    # print("Pose:", pose)
    # Transform to global coordinates
    # updated_pose_matrix = np.dot(pose, tof_extrinsic_matrix)
    points_global = np.dot(pose, points_camera)

    # Extract the transformed X, Y, Z coordinates
    X_global = points_global[0, :] / points_global[3 , :]
    Y_global = points_global[1, :] / points_global[3 , :]
    Z_global = points_global[2, :] / points_global[3 , :]
    # Stack the global coordinates
    point_cloud_global = np.vstack((X_global, Y_global, Z_global)).T

    # Create an Open3D PointCloud
    pcd = o3d.geometry.PointCloud()
    # Set the points in the PointCloud
    pcd.points = o3d.utility.Vector3dVector(point_cloud_global)

    # Flip the point cloud
    pcd.transform([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0],[0, 0, 0, 1]])

    # Add color to the point cloud
    pcd.colors = o3d.utility.Vector3dVector(rgb_values)
    
    # Save the point cloud to a file
    # ply_file_path = os.path.join(ply_path, frame_id + ".ply")    
    # o3d.io.write_point_cloud(ply_file_path, pcd)

    # Merge current point cloud with the overall point cloud
    point_cloud += pcd

    # Clear memory
    depth_image = None
    color_image = None
    depth_array = None
    color_array = None
    pcd = None


# Create an Open3D mesh representing coordinate axes
axes = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])

# Visualize the final point cloud
o3d.visualization.draw_geometries([point_cloud, axes])

pcd = None
point_cloud = None
axes = None

  0%|          | 0/5 [00:00<?, ?it/s]

Frame: 0000
G:\Universitat Siegen\SA\P-GPU\Code\gaussian-splatting\data\RGBD_Data\SyntheticV2\gt_depth\gt-rgb-depth-0000.png
Pose: [[-1.          0.00000004 -0.00000008  0.5       ]
 [-0.          0.866025    0.5         1.        ]
 [ 0.00000009  0.5        -0.866025    2.3       ]
 [ 0.          0.          0.          1.        ]]


 20%|██        | 1/5 [00:00<00:01,  3.68it/s]

Frame: 0010
G:\Universitat Siegen\SA\P-GPU\Code\gaussian-splatting\data\RGBD_Data\SyntheticV2\gt_depth\gt-rgb-depth-0010.png
Pose: [[-0.999848    0.00000004 -0.0174525   0.496667  ]
 [-0.0087262   0.866025    0.499924    0.983333  ]
 [ 0.0151143   0.5        -0.865893    2.32887   ]
 [ 0.          0.          0.          1.        ]]


 40%|████      | 2/5 [00:00<00:00,  3.66it/s]

Frame: 0020
G:\Universitat Siegen\SA\P-GPU\Code\gaussian-splatting\data\RGBD_Data\SyntheticV2\gt_depth\gt-rgb-depth-0020.png
Pose: [[-0.999391    0.00000004 -0.0348996   0.493333  ]
 [-0.0174497   0.866025    0.499695    0.966667  ]
 [ 0.0302239   0.5        -0.865498    2.35773   ]
 [ 0.          0.          0.          1.        ]]


 60%|██████    | 3/5 [00:00<00:00,  3.56it/s]

Frame: 0030
G:\Universitat Siegen\SA\P-GPU\Code\gaussian-splatting\data\RGBD_Data\SyntheticV2\gt_depth\gt-rgb-depth-0030.png
Pose: [[-0.998629    0.00000004 -0.052336    0.49      ]
 [-0.026168    0.866025    0.499315    0.95      ]
 [ 0.0453244   0.5        -0.864838    2.3866    ]
 [ 0.          0.          0.          1.        ]]


 80%|████████  | 4/5 [00:01<00:00,  3.47it/s]

Frame: 0040
G:\Universitat Siegen\SA\P-GPU\Code\gaussian-splatting\data\RGBD_Data\SyntheticV2\gt_depth\gt-rgb-depth-0040.png
Pose: [[-0.997564    0.00000004 -0.0697565   0.486667  ]
 [-0.0348782   0.866025    0.498782    0.933333  ]
 [ 0.060411    0.5        -0.863916    2.41547   ]
 [ 0.          0.          0.          1.        ]]


100%|██████████| 5/5 [00:01<00:00,  3.35it/s]
